[package]
name = "egui-gizmo-demo"
version = "0.1.0"
authors = ["Urho Laukkarinen <urho.laukkarinen@gmail.com>"]
edition = "2021"

license = "MIT"

[dependencies]
macroquad = "0.3.6"
egui = "0.16.1"
egui-macroquad = "0.8.0"
egui-gizmo = { path = ".." }