[package]
name = "egui-gizmo-demo"
version = "0.1.0"
authors = ["Urho Laukkarinen <urho.laukkarinen@gmail.com>"]
edition = "2021"

license = "MIT"

[dependencies]
macroquad = "0.3.10"
egui = "0.15.0"
egui-macroquad = "0.7.0"
egui-gizmo = { path = ".." }